### ISSUE TITLE
Segfault when checking config

### ISSUE THREAD

**Issue by mppace** [naemon/naemon-core#305]
I'm using naemon 1.0.5 on centos 7 and when i'm checking the config i get a segfault. looks like something to do with adding commands to a contact in the configuration, but the backtrace doesn't really help me in pointing out where the problem lies.

This is the backtrace output, any help would be greatly apprecitated.

gdb 

wproc: Registry request: name=Core Worker 4338;pid=4338
wproc: Registry request: name=Core Worker 4339;pid=4339
wproc: Registry request: name=Core Worker 4340;pid=4340
wproc: Registry request: name=Core Worker 4341;pid=4341
wproc: Registry request: name=Core Worker 4342;pid=4342
wproc: Registry request: name=Core Worker 4343;pid=4343
wproc: Registry request: name=Core Worker 4344;pid=4344
wproc: Registry request: name=Core Worker 4345;pid=4345
wproc: Registry request: name=Core Worker 4347;pid=4347
wproc: Registry request: name=Core Worker 4346;pid=4346
wproc: Registry request: name=Core Worker 4348;pid=4348
wproc: Registry request: name=Core Worker 4349;pid=4349

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff79528c5 in add_host_notification_command_to_contact () from /usr/lib64/naemon/libnaemon.so.0
(gdb) bt
#0  0x00007ffff79528c5 in add_host_notification_command_to_contact () from /usr/lib64/naemon/libnaemon.so.0
naemon/naemon#1  0x00007ffff796edf9 in ?? () from /usr/lib64/naemon/libnaemon.so.0
naemon/naemon#2  0x00007ffff79617ad in ?? () from /usr/lib64/naemon/libnaemon.so.0
naemon/naemon#3  0x00007ffff7655544 in g_tree_foreach () from /lib64/libglib-2.0.so.0
naemon/naemon#4  0x00007ffff796f707 in ?? () from /usr/lib64/naemon/libnaemon.so.0
naemon/naemon#5  0x00007ffff797624f in xodtemplate_read_config_data () from /usr/lib64/naemon/libnaemon.so.0
naemon/naemon#6  0x000000000040350f in main ()

(gdb)

**Comment by sni** [comment]
Is still an issue? If so, could you provide the command which caused the segfault?
